### ISSUE TITLE
enable usage via @property annotation

### ISSUE THREAD

**Issue by morbidick** [morbidick/lit-element-notify#2]

**Comment by justinfagnani** [comment]
Oops, I thought this would fall out naturally and I posted an example with decorators! So... /subscribe :)

**Comment by morbidick** [comment]
could be, i havent tested it yet, since im currently not using typescript or any other transform tools in my pipeline. Im thinking about adding type annotations and will have a try with the decorators. 

Looking at the decorator code it might be a better idea to extend `createProperty` instead of accessing the `properties` object directly.
