### ISSUE TITLE
Consider capitalizing `notify`

### ISSUE THREAD

**Issue by justinfagnani** [morbidick/lit-element-notify#3]
One style variation my teams have adopted for mixins is to capitalize mixin names even though they're functions, because somewhat like classes they often conceptually define a type.

**Comment by morbidick** [comment]
yeah thx for the input, im thinking about renaming it to LitNotify to emphasize the dependency on LitElement, what do you think?

**Comment by justinfagnani** [comment]
That seems perfectly reasonable too :)
