### ISSUE TITLE
Fix camelCase to kebab-case conversion

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [morbidick/lit-element-notify#6]
Currently, `notify: true` for `camelCase` property fires `camelcase-changed` events instead of `camel-case-changed` (like in Polymer).

**Comment by morbidick** [comment]
Yes, im trying to find the middleground between LitElement and PolymerElement. This follows the attribute reflection behaviour from LitElement.. This should be clearer from the Readme, maybe someone better with words (than me) could do a PR? :)

**Comment by morbidick** [comment]
Hi @FluorescentHallucinogen i just merged the bind directive (now subscribe) and extended the readme, maybe you could have a look. I hope this makes the differences between LitElement notify and the PoylmerElement clearer.
