### ISSUE TITLE
Implement 'value' for properties mixin

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [morbidick/lit-element-notify#7]
Currently there is no `value` (like in Polymer) for properties in LitElement:

```js
static get properties() {
  return {
    mood: {
      type: String,
      value: 'happy' // it doesn't work
    }
  };
}
```

It's possible to define the default values in the `constructor()`:

```js
constructor() {
  super();
  this.mood = 'happy';
}
```

But from my point of view it's not a good solution, because properties definition and default values are separated.

It's also possible to use the `@property` decorator and define properties and default values in one place:

```js
@property({ type: String }) mood = 'happy';
```

But it requires compiler that supports them, like TypeScript or Babel.

**Comment by morbidick** [comment]
I think this is outside the scope of this project and could be solved by another mixin. Personnally I'm looking forward to decorators and class fields coming to the platform.

**Comment by FluorescentHallucinogen** [comment]
@morbidick I agree that this should be a separate mixin.

BTW, shouldn't the [bind directive](https://github.com/morbidick/lit-element-notify/pull/5) also be a separate mixin? :thinking:

**Comment by morbidick** [comment]
@FluorescentHallucinogen since the two are strongly related and both tree shakeable i think its best to put them (and their documentation) in one place. But all in all I want to put the emphasize on the notify mixin since the bind directive (or whatever name it will have in the end) can lead to bad coding style.

**Comment by morbidick** [comment]
Closing this for now, if someone implements a directive i would be happy to mention it in the readme :)

**Comment by FluorescentHallucinogen** [comment]
@morbidick What about something like this? :wink:

```js
export const DefaultValues = (baseElement) => class extends baseElement {
  constructor() {
    super(...arguments);
    if (this.constructor.properties) {
      const { properties } = this.constructor;
      const propertyNames = Object.keys(properties);
      propertyNames.forEach((propertyName) => {
        if (!this.hasOwnProperty(propertyName) && properties[propertyName].hasOwnProperty('value')) {
          this[propertyName] = properties[propertyName].value instanceof Function ? properties[propertyName].value() : properties[propertyName].value;
        }
      });
    }
  }
}

export default DefaultValues;
```

**Comment by morbidick** [comment]
@FluorescentHallucinogen This looks similar to the first implementation i had for the notify mixin. You might be able to hook into the `createProperty` call from LitElement. Do you want to open a PR or publish it in a separate Repository?
